version: "3.7"

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - 'mysql'
    restart: on-failure
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DB: FEC_Bookings
    command: sh -c 'npm start'

  mysql:
    ports:
      - 3306
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword